name = "farhan-profile-views"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "profile-views"
database_id = "90d5b53c-343e-41c4-bcab-a786ffe5451a"
